name: Windows

on: [push, pull_request]

jobs:
  Riot-Games-Servers:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "cheat-engine/cheat-engine"
          ref: "7.4"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        shell: cmd
        run: msbuild /t:clean /t:build DBKKernel\DBKKernel.vcxproj /p:Configuration="Release without sig" /p:Platform=x64 /p:PostBuildEventUseInBuild=false

      - name: Upload To Artifact_Global
        uses: actions/upload-artifact@main
        with:
          name: ${{ github.job }}
          path: Cheat Engine\bin
