name: Windows

on: workflow_dispatch

jobs:
  Riot-Games-Servers:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "Fanixtar/Cheat-Engine-Builds"

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Build Driver
        shell: cmd
        run: msbuild /t:clean /t:build DBKKernel\DBKKernel.vcxproj /p:Configuration="Release without sig" /p:Platform=x64 /p:PostBuildEventUseInBuild=false

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ github.job }}
          path: Cheat Engine\bin
